name: Daily Website Check

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 12:00 AM UTC
    - cron: '0 12 * * *' # Runs at 12:00 PM UTC

jobs:
  check-website:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests schedule

      - name: Run script
        run: |
          python app.py
